spring.application.name=forum

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/forum
spring.datasource.username=forum
spring.datasource.password=forum
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/forum.master.xml


#springdoc.packages-to-scan=com.billon.internal.ckk_gateway.rest
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.doc-expansion=false
springdoc.swagger-ui.groups-order=asc
springdoc.swagger-ui.default-models-expand-depth=0
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

jwt.secret=8f4a2d9c7b5e3f1a6d8e9c0b2a4f7e1d3c5b8a9f2e6d4c1b7a0e3f8d5c9b2a6e4f1d7e0a3c6b9f2d5e8a1c4b7f0e3d6a9c2f5e8b1d4a7e0c3f6b9a2d5e8f1c4b7a0e3d6